name: Weekly Code Email

on:
  schedule:
    # Run every Monday at 11:20 AM UTC (which is 6:20 AM EST)
    - cron: '20 11 * * 1'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv  # Ensure dotenv is installed

      # Step 4: Run the Python script
      - name: Run weekly code script
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FAMILY_EMAIL_1: ${{ secrets.FAMILY_EMAIL_1 }}
          FAMILY_EMAIL_2: ${{ secrets.FAMILY_EMAIL_2 }}
          FAMILY_EMAIL_3: ${{ secrets.FAMILY_EMAIL_3 }}
          FAMILY_EMAIL_4: ${{ secrets.FAMILY_EMAIL_4 }}
        run: python generate.py
